title: "rna_mod"
description: "this is for RNA004 pipline expreience"
baseurl: "/skills-github-pages" 
url: "https://xiaokaixuan12333.github.io" 
  
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# 允许的插件
whitelist:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock



