title: "rna_mod"
description: "this is for RNA004 pipline expreience"
baseurl: "/skills-github-pages" 
url: "https://xiaokaixuan12333.github.io" 

# Jekyll 配置
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 允许的插件
whitelist:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock

